CREATE DATABASE users_db;

USE users_db;

CREATE TABLE UsersTable(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL,
	surname VARCHAR(100),
	personID VARCHAR(12) NOT NULL UNIQUE, 
	uuid BINARY(16) NOT NULL UNIQUE
);

